/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sunny_md5test_JNIProcess */

#ifndef _Included_com_sunny_md5test_JNIProcess
#define _Included_com_sunny_md5test_JNIProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sunny_md5test_JNIProcess
 * Method:    getInfoMD5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sunny_md5test_JNIProcess_getInfoMD5
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
